name: Deployment

on:
  push:
    branches:
      - main
      - staging

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
      matrix:
        value:
          [
            'bonds',
            'carbonmark',
            'protocol-metrics',
            'vesting',
            'user-carbon',
            'pairs',
            'celo-bridged-carbon',
            'ethereum-bridged-carbon',
            'polygon-bridged-carbon',
            'polygon-digital-carbon',
          ]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: '${{ matrix.value }}'

      # Generate code and check for uncommitted changes
      # https://github.com/marketplace/actions/check-uncommitted-changes
      - name: Generate Subgraph Code
        run: npm run codegen
        working-directory: '${{ matrix.value }}'
      - name: Check for uncommitted changes
        id: check-changes
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Evaluate if there are changes
        if: steps.check-changes.outputs.outcome == failure()
        run: echo "There are uncommitted changes - execute 'npm run codegen' locally and commit the generated files!"

      - name: Build Subgraph
        run: npm run build
        working-directory: '${{ matrix.value }}'
      # TODO: add matchstick test suite
      # - name: Run Tests
      #   run: npm run test
      #   working-directory: "${{ matrix.value }}"

      - name: Staging or not
        id: staging_or_not
        run: |
          if [ $REF == "refs/heads/staging" ]
          then
              PREFIX="staging-"
          fi;

          if [[ "${{ matrix.value }}" =~ .*"-carbon".* ]]
          then
              echo "subgraph=${PREFIX}${{ matrix.value }}" >> $GITHUB_OUTPUT
          else
              echo "subgraph=${PREFIX}klimadao-${{ matrix.value }}" >> $GITHUB_OUTPUT
          fi
        env:
          REF: ${{ github.ref }}
      - name: Deploy Subgraph
        run: ../node_modules/.bin/graph deploy --product hosted-service --deploy-key ${{ secrets.HOSTED_SERVICE_ACCESS_TOKEN }} klimadao/${{ steps.staging_or_not.outputs.subgraph }}
        working-directory: '${{ matrix.value }}'